### PR TITLE
Fixes #42 - overloaded methods to accept a message

### LINKED ISSUE #42: Add message to JSONAssert
I would love to be able to include a message to JSONAssert.assertEquals in the beginning of the method invocation:

``` java
assertEquals("expected should equal actual", expected, actual, false);
```

### PR DESCRIPTION
**Pull request by yasin3061**
- Overloaded equals() ans notEquals() methods to accept a message
- Junits for all the possible new overloads
- improvements in some of the existing junits

### CODE REVIEW

**Comment by yasin3061** [comment]
Hey @carterpage, this one fixes #42 
Please review the PR and let me know if you have any comments.
Thanks.

**Comment by carterpage** [comment]
Did you run 'mvn test'? I'm getting test errors.

[org.skyscreamer.jsonassert.ArrayValueMatcherTest.txt](https://github.com/skyscreamer/JSONassert/files/852674/org.skyscreamer.jsonassert.ArrayValueMatcherTest.txt)
[org.skyscreamer.jsonassert.comparator.ArraySizeComparatorTest.txt](https://github.com/skyscreamer/JSONassert/files/852675/org.skyscreamer.jsonassert.comparator.ArraySizeComparatorTest.txt)

**Comment by yasin3061** [comment]
Hey @carterpage, I am not sure how did I miss that.

Anyway, it was the minor fix and I have updated the PR.

Thanks for highlighting this.

**Comment by carterpage** [comment]
Thanks. Props for the extensive unit tests.

**Comment by yasin3061** [comment]
I will look for another issue to be fixed. Let me know if you have something in your mind.

**Pull request merged**
