### PR TITLE
use proper json library

### PR DESCRIPTION
**Pull request by imanushin**
Replace android library to official one, according to https://stackoverflow.com/a/2611900/185498

### CODE REVIEW

**Comment by carterpage** [comment]
This doesn't compile because the library doesn't support putting a null into JSONArray.

I'm all for getting off the old vaadin library. But need to be thoughtful about it. This would involve at least a minor version bump. Open to suggestions.

**Comment by imanushin** [comment]
@carterpage , thank you. Let's me do the following:
1. Add some build (will try to play with github actions)
2. Start testing during that build. Will check also code coverage and maybe will find some missing spots (hopefully it will work with maven)
3. Change dependency and check code change required
4. Return to this thread.

**Comment by carterpage** [comment]
Thank you, I'll keep an eye out for it.

**Comment by SheheryarAamir** [comment]
@carterpage we are having a conflict in our project with `spring-cloud-function` (version 4.1.2)  transitive dependency `org.json`. Would it be possible if this can be merged and released in 1.5.2

**Comment by carterpage** [comment]
Thanks for your submission. This should be address in #194.

A few more things were needed to make the change, including handling the change of JSONException to a RuntimeException.

**Pull request closed without merging**
